export const metadata = {
  title: "Akwaaba-Airlines",
  description: "Generated by create next app",
};

export default function FlightLayout({ children }) {
  return (
    <div>
      <div>
        {children}
      </div>
    </div>
  );
}
